default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: [ update_gems ]
      processes: 1
      threads: 1
      polling_interval: 1
    - queues: [ docparse ]
      processes: 1
      threads: 1
      polling_interval: 0.1
    - queues: [ default ]
      processes: 1
      threads: 1
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
