default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: [docparse]
      processes: 1
      threads: 4
      polling_interval: 0.5
    - queues: [default, update_gems]
      processes: 1
      threads: 3
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
