# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

default: &default
  update_remote_gems:
    class: UpdateRemoteGemsListJob
    schedule: every 10 minutes

  register_libraries:
    class: RegisterLibrariesJob
    schedule: every 15 minutes

  reap_old_containers:
    class: ReapGenerateDocsJob
    schedule: every 5 minutes

  delete_old_docs:
    class: CleanupUnvisitedDocsJob
    queue: default
    schedule: every 1 week

development:
  <<: *default

production:
  <<: *default
